name: Latest blog post workflow
on:
  schedule:
    - cron: "0 * * * *"
      workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://dev.to/feed/israelmitolu"
          comment_tag_name: DEV
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://www.freecodecamp.org/news/author/israelmitolu/rss"
          comment_tag_name: FCC
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://israelmitolu.hashnode.dev/rss.xml"
          comment_tag_name: BLOG
